---
- hosts: "{{ target | default('no_hosts')}}"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
  tasks:
  - name: change the remote root user password
    user: 
      name: root 
      update_password: always 
      password: $1$C0aJuGs6$puLk3LYqKS2wVgNTfxKoO1

